# Generated by Django 5.1.2 on 2024-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
