# Generated by Django 5.0.7 on 2024-09-18 07:17

import django.db.models.deletion
import product.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', product.fields.ThumbImageField(upload_to='product/%Y/%m')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('description', models.TextField(blank=True, verbose_name='Product Description')),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('create_dt', models.DateField(auto_now_add=True)),
                ('update_dt', models.DateField(auto_now=True)),
                ('owner', models.CharField(default='Kurly', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
